version: '3'

services:
  nginx_front:
    image: nginx:1.15.6-alpine
    volumes:
      - ./vue/frontend:/var/www
      - ./nginx_front/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front_vue
    ports:
     - "8000:80"
     - "443:443"

  front_vue:
    build: ./vue
    volumes:
      - ./vue/frontend:/var/www
    ports:
     - "80:8000"
    depends_on:
      - nginx_back

  nginx_back:
    image: nginx:1.15.6-alpine
    ports:
      - "8080:80"
    depends_on:
      - backend_php
    volumes:
      - ./src/my-app:/var/www
      - ./nginx_back/default.conf:/etc/nginx/conf.d/default.conf

  backend_php: 
    build: ./php
    volumes:
      - ./src/my-app:/var/www
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
 db-data: # mysql persistence 

  